### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by chenlian123** [HollyFang/homework#1]
需要改进的点：
1.项目要求使用jQuery 父类子类用了原生
2.没有把+1操作AddOne从类中抽离出纯函数，造成了测试对变量的依赖过强
3.挂在组件部分过于复杂
优点：
1.考虑的参数细节比较到位 整体流程以及对ES6初步已理解
2.package包管理规范

**Comment by lgwebdream** [comment]
hi 红菱，Usually familiar with the use of NODE_ENV development, repeat the configuration file can be omitted a lot. Such as testing the file, in fact, NODE_ENV as long as a copy. The demand is completed or consistent, continue to refuel. From your usual answers and efforts to look up, I think you will be good after the bar. (๑•̀ㅂ•́)و✧ refueling 😁

**Comment by HollyFang** [comment]
好的，谢谢老师。前两个问题是我对作业要求理解不够准确。“挂载组件部分过于复杂”这句我没能理解，麻烦稍微说明下好么？

**Comment by HollyFang** [comment]
@chenlian123 好的，谢谢老师。前两个问题是我对作业要求理解不够准确。“挂载组件部分过于复杂”这句我没能理解，麻烦稍微说明下好么？

**Comment by HollyFang** [comment]
@lgwebdream  Thank you for your encouragement, sir. I'll keep fighting~
